<?php
/**
 * ISO 20022 Address Structuring Game
 * Copyright (C) 2026 https://github.com/xdubois-57/iso20022-address-game
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

// Writes a scratch config/credentials.php for the Playwright E2E harness
// (scripts/e2e.sh) — same shape App\Controllers\SetupController::saveConfig()
// writes for a real install, not the legacy db_config.json format, which can
// only hold the database block. App\Models\Encryption reads the encryption
// key from this exact path unconditionally (it does not honour
// ISO20022_CONFIG_DIR — see its own constructor), so a db_config.json-only
// scratch instance would 500 the moment anything touches the leaderboard
// (LeaderboardModel, instantiated on every GET in public/index.php's poor
// man's cron). Usage:
//   php scripts/e2e-seed-config.php <sqlite-path> <credentials.php-path>

[, $sqlitePath, $credFile] = $argv;

$encryptionKey = bin2hex(random_bytes(32));
$pinHash = password_hash('1234', PASSWORD_BCRYPT);

$content = "<?php\n"
    . "// Generated by scripts/e2e-seed-config.php — throwaway, not a real install.\n"
    . "return [\n"
    . "    'db' => [\n"
    . "        'driver' => 'sqlite',\n"
    . "        'path' => " . var_export($sqlitePath, true) . ",\n"
    . "    ],\n"
    . "    'encryption' => [\n"
    . "        'key' => " . var_export($encryptionKey, true) . ",\n"
    . "    ],\n"
    . "    'admin' => [\n"
    . "        'pin' => " . var_export($pinHash, true) . ",\n"
    . "    ],\n"
    . "];\n";

file_put_contents($credFile, $content);
echo "Seeded {$credFile}\n";
