#!/usr/bin/env bash
#
# ISO 20022 Address Structuring Game
# Copyright (C) 2026 https://github.com/xdubois-57/iso20022-address-game
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# scripts/release-lib.sh - the parts of release.sh a test can reach.
#
# WHY THIS FILE EXISTS
# ---------------------------------------------------------------------------
# release.sh shipped config/deploy.conf - the production FTP host, user and
# password - inside the deployable zip attached to v0.3.1, v0.3.2 and v0.3.3.
# Every gate was green for all three. They were always going to be: PHPUnit,
# PHPStan, Playwright, ZAP and CodeQL read the source, and the archive people
# download was the one artifact nothing inspected.
#
# It could not have been caught, either, because there was nothing to call. The
# whole release was one linear script that tags, pushes and publishes as it
# goes, so "check the exclusion list is right" meant "cut a release and look".
#
# So the decisions worth testing live here as functions, and release.sh sources
# them. The point is that there is exactly one copy: a test that reimplemented
# the exclusion list would pass while the real list stayed wrong, which is a
# more comfortable version of the failure this file exists to prevent.
#
# What stays in release.sh is everything irreversible - the tag, the push, the
# pull request, the publish. None of that is testable without doing it, and
# none of it is where the bug was.
#
# Sourced, not executed:  . "$SCRIPT_DIR/scripts/release-lib.sh"

# ── Version arithmetic ──────────────────────────────────────────────────────
#
# Prints the next tag for a bump against a current tag. Pure: no git, no
# network, no files, which is what makes the awkward cases cheap to pin down -
# a bumped minor zeroes the patch, a bumped major zeroes both, and a repository
# with no tags at all starts from v0.0.0 rather than producing "v.1".
release_next_version() {
    local bump="$1" latest="${2:-}"
    local major minor patch

    [[ -z "$latest" ]] && latest="v0.0.0"

    IFS='.' read -r major minor patch <<< "${latest#v}"

    # A tag that is not three numbers is a mistake worth stopping on rather
    # than turning into an arithmetic error further down.
    if [[ ! "$major" =~ ^[0-9]+$ || ! "$minor" =~ ^[0-9]+$ || ! "$patch" =~ ^[0-9]+$ ]]; then
        echo "release_next_version: '$latest' is not a vMAJOR.MINOR.PATCH tag" >&2
        return 1
    fi

    # Forced to base 10. Bash reads a leading zero as octal, so a v0.0.08 tag
    # made `$((patch + 1))` die with "value too great for base" — the release
    # stopping on an arithmetic error rather than on anything about the release.
    # Normalising here also means the tag that comes out has no leading zeros,
    # which is what semver asks for anyway.
    major=$((10#$major)); minor=$((10#$minor)); patch=$((10#$patch))

    case "$bump" in
        major) major=$((major + 1)); minor=0; patch=0 ;;
        minor) minor=$((minor + 1)); patch=0 ;;
        patch) patch=$((patch + 1)) ;;
        *) echo "release_next_version: unknown bump '$bump'" >&2; return 1 ;;
    esac

    printf 'v%s.%s.%s\n' "$major" "$minor" "$patch"
    return 0
}

# ── The version stamp ───────────────────────────────────────────────────────
#
# The generated config/version.php. It is read by the running site, so it has
# to be valid PHP returning an array with both keys - a stamp that parses but
# says the wrong thing is invisible until somebody reads the footer in
# production.
release_write_version_file() {
    local path="$1" tag="$2" commit="$3"

    cat > "$path" <<EOF
<?php
// Auto-generated by release.sh — do not edit manually
return [
    'tag' => '$tag',
    'commit' => '$commit',
];
EOF
    return $?
}

# ── What must not reach the artifact ────────────────────────────────────────
#
# Anything under config/ that git does not track is, by construction, local: a
# credentials file, a deploy password, a database DSN. Printed one per line.
#
# The inversion is the fix. The old exclusion list named two credentials files
# by hand and missed the third when it arrived, and nothing failed when it did
# - the zip built happily and the secret shipped. A file is now excluded for
# being untracked rather than for having been remembered, so one added tomorrow
# is covered the day it is created.
release_config_excludes() {
    git ls-files --others -- config/
    return $?
}

# ── Building the artifact ───────────────────────────────────────────────────
#
# A ready-to-upload copy of the site. vendor/ must be in it: shared hosting has
# no way to run `composer install`, and a vendor-less zip uploads perfectly
# happily and yields a dead site the moment a class it needs is not there.
# GitHub's auto-generated source zipball is NOT a substitute, for that reason.
#
# The caller is responsible for having run `composer install --no-dev` first.
# This function only decides what goes in.
#
# The `* <digit>` patterns drop macOS conflict copies - "phpunit 2",
# "README 3.md", "deep-copy 4/". iCloud Drive creates them when a synced folder
# is rewritten mid-sync, which is exactly what `composer install` does to
# vendor/bin/* and autoload_files.php, so a checkout living under a synced
# ~/Documents grows them steadily: v0.2.3 shipped 56 of them, ~229 KB of dead
# weight including dev-only binaries the build is meant to strip.
#
# The development toolchain block is next. None of it is reachable over the web
# - scripts/ and the dotfiles are denied by .htaccess - but none of it belongs
# on a web host either, and `scripts/dast*` in particular is a scanner harness
# that exists to be pointed at a running instance. Shipping it is not an
# exploit; it is handing someone the tools and saving them the download.
release_build_artifact() {
    local artifact="$1"
    local config_excludes=()

    while IFS= read -r stray; do
        [[ -n "$stray" ]] && config_excludes+=("$stray")
    done < <(release_config_excludes)

    if (( ${#config_excludes[@]} > 0 )); then
        echo "Excluding ${#config_excludes[@]} untracked file(s) under config/:"
        printf '  %s\n' "${config_excludes[@]}"
    fi

    rm -f "$artifact"

    zip -rq "$artifact" . \
        -x ".git/*" ".github/*" "tests/*" "storage/*" "uploads/*" "*.zip" \
           "config/credentials.php" "config/db_config.json" \
           "node_modules/*" "coverage/*" "test-results/*" "playwright-report/*" \
           ".claude/*" ".idea/*" ".vscode/*" "*.DS_Store" "deploy.sh" \
           "scripts/dast*" "scripts/e2e*" "scripts/serve.sh" \
           "scripts/merge-coverage.php" "scripts/js-typecheck.mjs" \
           "scripts/release-lib.sh" \
           "phpstan.neon" "phpstan-baseline.neon" "js-typecheck-baseline.json" \
           "tsconfig.json" "phpunit.xml" "vitest.config.js" \
           "package.json" "package-lock.json" "sonar-project.properties" \
           "DESIGN.md" "docs/*" "release.sh" \
           "* [0-9]" "* [0-9].*" "* [0-9]/" "* [0-9]/*" \
           "* [0-9][0-9]" "* [0-9][0-9].*" "* [0-9][0-9]/" "* [0-9][0-9]/*" \
           ${config_excludes[@]+"${config_excludes[@]}"}
    return $?
}

# ── The three things asserted about a built artifact ────────────────────────
#
# Each returns non-zero and says what is wrong, leaving the caller to decide
# how loudly to fail. They run before anything is attached to a Release, so a
# surprise costs a re-run rather than a published bad artifact.

# The guard that matters. The exclusion is a promise; this is the check that it
# held, and both derive from `git ls-files` so they cannot drift apart the way
# two hand-maintained lists would.
release_assert_no_local_secrets() {
    local artifact="$1"
    local tracked shipped leaked

    tracked=$(git ls-files -- config/ | sort)
    shipped=$(unzip -Z1 "$artifact" | grep '^config/' | grep -v '/$' | sort || true)
    leaked=$(comm -13 <(printf '%s\n' "$tracked") <(printf '%s\n' "$shipped"))

    if [[ -n "$leaked" ]]; then
        echo "$artifact contains file(s) under config/ that git does not track:" >&2
        printf '  %s\n' $leaked >&2
        echo "Those are local files — credentials, deploy passwords, database settings." >&2
        return 1
    fi
    return 0
}

# Counted rather than `grep -q`: -q exits on the first match, unzip then dies on
# SIGPIPE, and under `set -o pipefail` the pipeline reports 141 even though the
# file was found. That turned this guard into the opposite of a guard - it
# blocked v0.2.5 over an artifact that was perfectly fine.
release_assert_has_autoload() {
    local artifact="$1"
    local autoload

    autoload=$(unzip -Z1 "$artifact" | grep -c '^vendor/autoload.php$' || true)
    if [[ "$autoload" -eq 0 ]]; then
        echo "$artifact has no vendor/autoload.php — it would deploy as a dead site." >&2
        return 1
    fi
    return 0
}

release_assert_no_stray_copies() {
    local artifact="$1"
    local strays

    strays=$(unzip -Z1 "$artifact" | grep -cE ' [0-9]+(/|\.|$)' || true)
    if [[ "$strays" -gt 0 ]]; then
        echo "$artifact contains $strays macOS conflict copies:" >&2
        unzip -Z1 "$artifact" | grep -E ' [0-9]+(/|\.|$)' | head -10 >&2
        return 1
    fi
    return 0
}
