<?php
/**
 * ISO 20022 Address Structuring Game
 * Copyright (C) 2026 https://github.com/xdubois-57/iso20022-address-game
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

namespace App\Controllers;

use App\Models\Database;

class SetupController
{
    /**
     * POST /api/setup/test — Test a DB connection with provided credentials.
     */
    public function testConnection(): void
    {
        $input = $this->getJsonInput();
        $dbConfig = [
            'host' => trim($input['host'] ?? '127.0.0.1'),
            'port' => trim($input['port'] ?? '3306'),
            'name' => trim($input['name'] ?? ''),
            'username' => trim($input['username'] ?? ''),
            'password' => $input['password'] ?? '',
        ];

        if (empty($dbConfig['name'])) {
            $this->jsonResponse(['error' => 'Database name is required'], 400);
            return;
        }

        $db = Database::getInstance();
        if ($db->tryConnect($dbConfig)) {
            $this->jsonResponse(['success' => true, 'message' => 'Connection successful']);
        } else {
            $this->jsonResponse(['error' => 'Could not connect to the database with the provided credentials'], 400);
        }
    }

    /**
     * POST /api/setup/save — Save DB config, generate encryption key, initialize schema.
     */
    public function saveConfig(): void
    {
        $input = $this->getJsonInput();
        $dbConfig = [
            'host' => trim($input['host'] ?? '127.0.0.1'),
            'port' => trim($input['port'] ?? '3306'),
            'name' => trim($input['name'] ?? ''),
            'username' => trim($input['username'] ?? ''),
            'password' => $input['password'] ?? '',
        ];

        if (empty($dbConfig['name'])) {
            $this->jsonResponse(['error' => 'Database name is required'], 400);
            return;
        }

        $db = Database::getInstance();
        if (!$db->tryConnect($dbConfig)) {
            $this->jsonResponse(['error' => 'Connection failed. Cannot save invalid credentials.'], 400);
            return;
        }

        // Generate secure encryption key (32 bytes = 64 hex chars)
        $encryptionKey = bin2hex(random_bytes(32));

        // Default admin PIN hashed with bcrypt
        $defaultPin = '1234';
        $hashedPin = password_hash($defaultPin, PASSWORD_BCRYPT);

        // Write credentials.php
        $credFile = __DIR__ . '/../../config/credentials.php';
        $credContent = "<?php\n";
        $credContent .= "/**\n";
        $credContent .= " * ISO 20022 Address Structuring Game\n";
        $credContent .= " * Auto-generated by setup on " . date('Y-m-d H:i:s') . "\n";
        $credContent .= " */\n\n";
        $credContent .= "return [\n";
        $credContent .= "    'db' => [\n";
        $credContent .= "        'host' => " . var_export($dbConfig['host'], true) . ",\n";
        $credContent .= "        'port' => " . var_export($dbConfig['port'], true) . ",\n";
        $credContent .= "        'name' => " . var_export($dbConfig['name'], true) . ",\n";
        $credContent .= "        'username' => " . var_export($dbConfig['username'], true) . ",\n";
        $credContent .= "        'password' => " . var_export($dbConfig['password'], true) . ",\n";
        $credContent .= "    ],\n";
        $credContent .= "    'encryption' => [\n";
        $credContent .= "        'key' => " . var_export($encryptionKey, true) . ",\n";
        $credContent .= "    ],\n";
        $credContent .= "    'admin' => [\n";
        $credContent .= "        'pin' => " . var_export($hashedPin, true) . ",\n";
        $credContent .= "    ],\n";
        $credContent .= "];\n";

        if (file_put_contents($credFile, $credContent) === false) {
            // Fallback: save to JSON config
            if (!$db->saveJsonConfig($dbConfig)) {
                $this->jsonResponse(['error' => 'Failed to write config file. Check directory permissions.'], 500);
                return;
            }
        }

        // Initialize schema
        $db->initSchema();

        $this->jsonResponse([
            'success' => true,
            'message' => 'Configuration saved and database initialized. Default admin PIN is 1234 — change it immediately.',
        ]);
    }

    private function getJsonInput(): array
    {
        $raw = file_get_contents('php://input');
        return json_decode($raw, true) ?? [];
    }

    private function jsonResponse(array $data, int $code = 200): void
    {
        http_response_code($code);
        header('Content-Type: application/json; charset=utf-8');
        echo json_encode($data);
    }
}
